Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/hhwwgg/TTGJets_2017/job_13/TTGJets_2017_executable_job13.py", line 4, in <module>
    from higgs_dna.analysis import run_analysis
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 10, in <module>
    import uproot
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/__init__.py", line 117, in <module>
    from uproot.writing import create
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/writing/__init__.py", line 26, in <module>
    from uproot.writing.writable import (
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/writing/writable.py", line 35, in <module>
    import uproot.writing._cascade
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/writing/_cascade.py", line 33, in <module>
    import uproot.models.TList
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1074, in get_data
OSError: [Errno 5] Input/output error
