ERROR:root:code for hash blake2b was not found.
Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/hashlib.py", line 261, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/hashlib.py", line 129, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2b
Traceback (most recent call last):
  File "/eos/user/z/zhenxuan/hhwwgg/TTToHadronic_2017/job_45/TTToHadronic_2017_executable_job45.py", line 13, in <module>
    run_analysis(config)
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 52, in run_analysis
    events, sum_weights = AnalysisManager.load_events(config["files"], config["branches"])
  File "/afs/cern.ch/user/z/zhenxuan/HiggsDNA/higgs_dna/analysis.py", line 465, in load_events
    with uproot.open(file, timeout = 500) as f:
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/reading.py", line 141, in open
    file = ReadOnlyFile(
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/reading.py", line 580, in __init__
    self._source = Source(
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 272, in __init__
    self._open()
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 275, in _open
    self._resource = XRootDResource(self._file_path, self._timeout)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 83, in __init__
    self._open()
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 92, in _open
    self._xrd_error(status)
  File "/eos/user/z/zhenxuan/higgs-dna/lib/python3.10/site-packages/uproot/source/xrootd.py", line 118, in _xrd_error
    raise OSError(
OSError: XRootD error: [ERROR] Operation expired
in file root://cms-xrd-global.cern.ch//store/mc/RunIIFall17NanoAODv7/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/NANOAODSIM/PU2017_12Apr2018_Nano02Apr2020_new_pmx_102X_mc2017_realistic_v8-v2/230000/E34B9614-8F9D-2242-B96B-E4AC3852B696.root
